version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: kbcs_v2_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=kbcs_telemetry
    volumes:
      - influxdb-data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: kbcs_v2_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/dashboards/kbcs_v2.json:/var/lib/grafana/dashboards/kbcs_v2.json
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data:
